CREATE TABLE NGUOISUDUNG
(
	MANGUOISUDUNG NCHAR(10),
	HOTEN NVARCHAR(50),
	MATKHAU NCHAR(10),
	NGAYSINH DATETIME,
	EMAIL NCHAR(20),
	HOPLE INT,
	PRIMARY KEY (MANGUOISUDUNG)
	
)

CREATE TABLE COSOVATCHAT
(
	MAVATCHAT NCHAR(10),
	TENVATCHAT NVARCHAR(50),
	MALOAI NCHAR(10),
	MATINHTRANG NCHAR(10),
	PRIMARY KEY (MAVATCHAT)
)

CREATE TABLE LOAIVATCHAT
(
	MALOAI NCHAR(10),
	TENLOAI NVARCHAR(50),
	PRIMARY KEY (MALOAI)
)

CREATE TABLE TINHTRANGVATCHAT
(
	MATINHTRANG NCHAR(10),
	TENTINHTRANG NVARCHAR(50),
	PRIMARY KEY (MATINHTRANG)
)

CREATE TABLE PHIEUYEUCAU
(
	MAPHIEU NCHAR(10),
	MANGUOISUDUNG NCHAR(10),
	MAVATCHAT NCHAR(10),
	THOIGIANDANGKI DATETIME,
	THOIGIANMUON DATETIME,
	MATINHTRANG NCHAR(10),
	GHICHU NVARCHAR(50),
	SOLUONG INT,
	PRIMARY KEY (MAPHIEU)
)

CREATE TABLE TINHTRANGYEUCAU
(
	MATINHTRANG NCHAR(10),
	TENTINHTRANG NVARCHAR(50),
	PRIMARY KEY (MATINHTRANG)
)

CREATE TABLE KETQUA
(
	MAKETQUA NCHAR(10),
	MANGUOISUDUNG NCHAR(10),
	YEUCAUTHANHCONG NCHAR(10),
	YEUCAUTHATBAI NCHAR(10),
	GHICHU NVARCHAR(50),
	PRIMARY KEY (MAKETQUA)
)

ALTER TABLE COSOVATCHAT
ADD CONSTRAINT FK_CSVC_TTVC
FOREIGN KEY (MATINHTRANG)
REFERENCES TINHTRANGVATCHAT(MATINHTRANG)
	
ALTER TABLE COSOVATCHAT
ADD CONSTRAINT FK_CSVC_LVC
FOREIGN KEY (MALOAI)
REFERENCES LOAIVATCHAT(MALOAI)

ALTER TABLE PHIEUYEUCAU
ADD CONSTRAINT FK_PYC_NSD
FOREIGN KEY (MANGUOISUDUNG)
REFERENCES NGUOISUDUNG(MANGUOISUDUNG)

ALTER TABLE PHIEUYEUCAU
ADD CONSTRAINT FK_PYC_CSVC
FOREIGN KEY (MAVATCHAT)
REFERENCES COSOVATCHAT(MAVATCHAT)

ALTER TABLE PHIEUYEUCAU
ADD CONSTRAINT FK_PYC_TTYC
FOREIGN KEY (MATINHTRANG)
REFERENCES TINHTRANGYEUCAU(MATINHTRANG)

ALTER TABLE KETQUA
ADD CONSTRAINT FK_KQ_NSD
FOREIGN KEY (MANGUOISUDUNG)
REFERENCES NGUOISUDUNG(MANGUOISUDUNG)